name: External Semantic Layer Sync
run-name: ${{ github.actor }} is uploading an external semantic layer 🚀
on: [push]
jobs:
  External-Semantic-Layer-Sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Archive repository
      run: git archive -o repo.zip HEAD

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Send archive via curl
      run: |
        response=$(curl -s -w "%{http_code}" -o response_body.json -X POST \
          -F "data=@repo.zip" \
          -F "syntax=LOOK_ML" \
          -F "dataConnectionId=5532da14-af66-4bfe-9e77-e2b90e1a33c7" \
          -F "verbose=true" \
          https://staging.hex.tech/api/v1/semantic-layer \
          -H "Authorization: Bearer ${{ secrets.HEXSEMANTICLAYERAPITOKEN }}")
        
        status_code="${response: -3}"
        response_body="${response::-3}"

        if [ "$status_code" -ne 201 ]; then
          echo "Error: Received status code $status_code"
          echo "Response Body:"
          echo "$response_body" | jq '.'
          exit 1
        fi
        
        echo "$response"
        echo "Formatted Response Body:"
        echo "$response_body" | jq '.'
